sudo: required
dist: trusty
language: r
r_binary_packages:
    - Rcpp
    - devtools
    - knitr
    - testthat
cache: packages
os:
    - linux
    - osx
addons:
  apt:
    packages: libmpfr-dev
  homebrew:
    packages: mpfr
script:
    - R CMD build .
    - R CMD check --as-cran *.tar.gz
