sudo: required
dist: trusty
language: r
r_binary_packages:
    - Rcpp
    - devtools
    - knitr
    - testthat
cache: packages
os:
    - linux
    - osx
before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; sudo apt-get install -qy libmpfr-dev; else brew outdated mpfr || brew upgrade mpfr; fi
script:
    - R CMD build .
    - R CMD check --as-cran *.tar.gz
