sudo: required
dist: trusty
language: r
r_binary_packages:
    - Rcpp
    - devtools
    - knitr
    - testthat
cache: packages
os:
    - linux
    - osx
before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; sudo apt-get install -qy libmpfr-dev; else if [ $(brew list | grep mpfr) ]; then brew upgrade mpfr ; else brew install mpfr; fi; fi
script:
    - R CMD build .
    - R CMD check *.tar.gz
